var DATA = [
      { id:0, label:"org.nnsoft.guice.rocoto.configuration", link:"org/nnsoft/guice/rocoto/configuration/package-summary.html", type:"package" },
      { id:1, label:"org.nnsoft.guice.rocoto.configuration.ConfigurationModule", link:"org/nnsoft/guice/rocoto/configuration/ConfigurationModule.html", type:"class" },
      { id:2, label:"org.nnsoft.guice.rocoto.configuration.binder", link:"org/nnsoft/guice/rocoto/configuration/binder/package-summary.html", type:"package" },
      { id:3, label:"org.nnsoft.guice.rocoto.configuration.binder.PropertyValueBindingBuilder", link:"org/nnsoft/guice/rocoto/configuration/binder/PropertyValueBindingBuilder.html", type:"class" },
      { id:4, label:"org.nnsoft.guice.rocoto.configuration.binder.XMLPropertiesFormatBindingBuilder", link:"org/nnsoft/guice/rocoto/configuration/binder/XMLPropertiesFormatBindingBuilder.html", type:"class" },
      { id:5, label:"org.nnsoft.guice.rocoto.configuration.resolver", link:"org/nnsoft/guice/rocoto/configuration/resolver/package-summary.html", type:"package" },
      { id:6, label:"org.nnsoft.guice.rocoto.configuration.resolver.PropertiesResolverProvider", link:"org/nnsoft/guice/rocoto/configuration/resolver/PropertiesResolverProvider.html", type:"class" },
      { id:7, label:"org.nnsoft.guice.rocoto.converters", link:"org/nnsoft/guice/rocoto/converters/package-summary.html", type:"package" },
      { id:8, label:"org.nnsoft.guice.rocoto.converters.AbstractConverter", link:"org/nnsoft/guice/rocoto/converters/AbstractConverter.html", type:"class" },
      { id:9, label:"org.nnsoft.guice.rocoto.converters.BigDecimalConverter", link:"org/nnsoft/guice/rocoto/converters/BigDecimalConverter.html", type:"class" },
      { id:10, label:"org.nnsoft.guice.rocoto.converters.BigIntegerConverter", link:"org/nnsoft/guice/rocoto/converters/BigIntegerConverter.html", type:"class" },
      { id:11, label:"org.nnsoft.guice.rocoto.converters.BitSetConverter", link:"org/nnsoft/guice/rocoto/converters/BitSetConverter.html", type:"class" },
      { id:12, label:"org.nnsoft.guice.rocoto.converters.CharsetConverter", link:"org/nnsoft/guice/rocoto/converters/CharsetConverter.html", type:"class" },
      { id:13, label:"org.nnsoft.guice.rocoto.converters.ClobConverter", link:"org/nnsoft/guice/rocoto/converters/ClobConverter.html", type:"class" },
      { id:14, label:"org.nnsoft.guice.rocoto.converters.CurrencyConverter", link:"org/nnsoft/guice/rocoto/converters/CurrencyConverter.html", type:"class" },
      { id:15, label:"org.nnsoft.guice.rocoto.converters.DateConverter", link:"org/nnsoft/guice/rocoto/converters/DateConverter.html", type:"class" },
      { id:16, label:"org.nnsoft.guice.rocoto.converters.DecimalFormatConverter", link:"org/nnsoft/guice/rocoto/converters/DecimalFormatConverter.html", type:"class" },
      { id:17, label:"org.nnsoft.guice.rocoto.converters.FileConverter", link:"org/nnsoft/guice/rocoto/converters/FileConverter.html", type:"class" },
      { id:18, label:"org.nnsoft.guice.rocoto.converters.InetAddressConverter", link:"org/nnsoft/guice/rocoto/converters/InetAddressConverter.html", type:"class" },
      { id:19, label:"org.nnsoft.guice.rocoto.converters.LocaleConverter", link:"org/nnsoft/guice/rocoto/converters/LocaleConverter.html", type:"class" },
      { id:20, label:"org.nnsoft.guice.rocoto.converters.PatternConverter", link:"org/nnsoft/guice/rocoto/converters/PatternConverter.html", type:"class" },
      { id:21, label:"org.nnsoft.guice.rocoto.converters.PropertiesConverter", link:"org/nnsoft/guice/rocoto/converters/PropertiesConverter.html", type:"class" },
      { id:22, label:"org.nnsoft.guice.rocoto.converters.SQLDateConverter", link:"org/nnsoft/guice/rocoto/converters/SQLDateConverter.html", type:"class" },
      { id:23, label:"org.nnsoft.guice.rocoto.converters.SQLTimeConverter", link:"org/nnsoft/guice/rocoto/converters/SQLTimeConverter.html", type:"class" },
      { id:24, label:"org.nnsoft.guice.rocoto.converters.SQLTimestampConverter", link:"org/nnsoft/guice/rocoto/converters/SQLTimestampConverter.html", type:"class" },
      { id:25, label:"org.nnsoft.guice.rocoto.converters.SimpleDateFormatConverter", link:"org/nnsoft/guice/rocoto/converters/SimpleDateFormatConverter.html", type:"class" },
      { id:26, label:"org.nnsoft.guice.rocoto.converters.TimeZoneConverter", link:"org/nnsoft/guice/rocoto/converters/TimeZoneConverter.html", type:"class" },
      { id:27, label:"org.nnsoft.guice.rocoto.converters.URIConverter", link:"org/nnsoft/guice/rocoto/converters/URIConverter.html", type:"class" },
      { id:28, label:"org.nnsoft.guice.rocoto.converters.URLConverter", link:"org/nnsoft/guice/rocoto/converters/URLConverter.html", type:"class" },
      { id:29, label:"org.nnsoft.guice.rocoto.converters.UUIDConverter", link:"org/nnsoft/guice/rocoto/converters/UUIDConverter.html", type:"class" }

    ];
